# Generated by Django 4.0.6 on 2022-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
